# Generated by Django 6.0.4 on 2026-04-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchedcity',
            options={'verbose_name': 'Searched City', 'verbose_name_plural': 'Searched Cities'},
        ),
    ]
