# Generated by Django 6.0.4 on 2026-04-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_searchedcity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('workout', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Saved Workout',
                'verbose_name_plural': 'Saved Workouts',
            },
        ),
    ]
