# Generated by Django 6.0.4 on 2026-04-19 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_savedworkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_comment', models.TextField(blank=True, max_length=250)),
                ('after_comment', models.TextField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.savedworkout')),
            ],
            options={
                'verbose_name': 'Workout Reflection',
                'verbose_name_plural': 'Workout Reflections',
            },
        ),
    ]
