# Generated by Django 6.0.4 on 2026-04-21 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workoutreflection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedworkout',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedworkout',
            name='workout_reflection_after',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='savedworkout',
            name='workout_reflection_before',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='savedworkout',
            name='workout',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='WorkoutReflection',
        ),
    ]
