# Generated by Django 6.0.4 on 2026-04-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workoutreflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedworkout',
            name='workout_reflection_after',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='savedworkout',
            name='workout_reflection_before',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='WorkoutReflection',
        ),
    ]
