# Generated by Django 4.2.20 on 2026-04-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_savedworkout_id_alter_searchedcity_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchedcity',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
